#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/rmuxid"

echo Setting up rmux

export VISUAL=vi

if [ -e /etc/profile ]; then
	source /etc/profile
fi

if [ -e "$HOME/.profile" ]; then
	source "$HOME/.profile"
fi

if [ -e "$HOME/.bash_profile" ]; then
	source "$HOME/.bash_profile"
fi

chmod 755 "$RMUXDIR/tmux-start"
alias script="script -c \"bash --rcfile '$RMUXDIR/init' -i\""
alias bash="bash --rcfile '$RMUXDIR/init' -i"
alias tmux="$RMUXDIR/tmux-start"
alias tmuc="$RMUXDIR/tmux-start attach -t"
alias tmuk="$RMUXDIR/tmux-start attach"
export VIMINIT="source $RMUXDIR/vimrc"
export LC_ALL="$LC_ALL"
export LANG="$LANG"
git config --global color.ui true 2> /dev/null

if [ "$TMUX" == "" ]; then
	echo Commands: tmuk = attach session 0, tmuc N = attach session N
	echo tmux sessions:
	tmux ls 2> /dev/null
	echo >> "$RMUXDIR/tmux.conf"
	echo "set-option -g default-command \"bash --rcfile '$RMUXDIR/init' -i\"" >> "$RMUXDIR/tmux.conf"
fi

gprfx=""
if [ -e /opt/csw/bin/gls ]; then
	gprfx="g"
fi
if [ -e /usr/bin/gls ]; then
	gprfx="g"
fi

source $RMUXDIR/bashrc

