#!/usr/bin/env bash
SCRIPT_DIR="$( dirname $( dirname $(cd ${0%/*} && echo $PWD/${0##*/}) ) )"
source $SCRIPT_DIR/rmuxid

echo Setting up rmux

export VISUAL=vi

if [ -e /etc/profile ]; then
	source /etc/profile
fi

if [ -e "$HOME/.profile" ]; then
	source "$HOME/.profile"
fi

if [ -e "$HOME/.bash_profile" ]; then
	source "$HOME/.bash_profile"
fi

chmod 755 "$RMUXDIR/tmux-start"
alias script="script -c \"bash --rcfile '$RMUXDIR/init' -i\""
alias bash="bash --rcfile '$RMUXDIR/init' -i"
alias tmux="$RMUXDIR/tmux-start"
alias tmuc="$RMUXDIR/tmux-start attach -t"
alias tmuk="$RMUXDIR/tmux-start attach"
git config --global color.ui true 2> /dev/null

if [ "$TMUX" == "" ]; then
	echo tmux sessions:
	tmux ls 2> /dev/null
	echo >> "$RMUXDIR/tmux.conf"
	echo "set-option -g default-command \"bash --rcfile '$RMUXDIR/init' -i\"" >> "$RMUXDIR/tmux.conf"
fi

gprfx=""
if [ -e /opt/csw/bin/gls ]; then
	gprfx="g"
fi
if [ -e /usr/bin/gls ]; then
	gprfx="g"
fi

__git_ps1 ()
{
	local b="$(git symbolic-ref HEAD 2>/dev/null)";
	if [ -n "$b" ]; then
		if [ -n "$s" ]; then
			s=",$s"
		fi
		printf " (%s)" "${b##refs/heads/}";# "$s";
	fi
}

export -f __git_ps1

export VIMINIT="source $RMUXDIR/vimrc"
export LC_ALL="$LC_ALL"
export LANG="$LANG"
export PS1="\[\033[00;32m\]\u\[\033[00;37m\]@\h \[\033[00;34m\]\w [\$(ls -1 | wc -l | sed 's: ::g') files, \$(${gprfx}ls -lah | ${gprfx}grep -m 1 total | ${gprfx}sed 's/total //')] \$(__git_ps1  )\n\[\033[00;33m\]$> \[\033[00m\]"

