#!/usr/bin/env bash
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$SCRIPT_DIR/rmuxid"

if [ -e "$RMUXDIR/bashpre" ]; then
	source "$RMUXDIR/bashpre"
fi

echo Setting up rmux

export VISUAL=vi

if [ -e /etc/profile ]; then
	source /etc/profile
fi

if [ -e "$HOME/.profile" ]; then
	source "$HOME/.profile"
fi

if [ -e "$HOME/.bash_profile" ]; then
	source "$HOME/.bash_profile"
fi

alias script="script -c \"bash --rcfile '$RMUXDIR/init' -i\""
alias bash="bash --rcfile '$RMUXDIR/init' -i"
alias rxsu="sudo -E bash --rcfile '$RMUXDIR/init' -i"
# only setup tmux and vim if they are configured
if [ -e "$RMUXDIR/tmux.conf" ]; then
	alias tmux="$RMUXDIR/tmux-start"
	alias tmuc="$RMUXDIR/tmux-start attach -t"
	alias tmuk="$RMUXDIR/tmux-start attach"
fi
if [ -e "$RMUXDIR/vimrc" ]; then
	export VIMINIT="source $RMUXDIR/vimrc"
fi

if [ "$TMUX" == "" ]; then
	echo "Commands:  rxsu     root privileges"
	if [ -e "$RMUXDIR/tmux.conf" ]; then
		echo "           tmuk     attach session 0"
		echo "           tmuc N   attach session N"
		echo tmux sessions:
		tmux ls 2> /dev/null
	fi
fi

export LANGUAGE=$LANG
source "$RMUXDIR/bashrc"

