#!/usr/bin/env bash

SCRIPT_DIR="$( dirname $(cd ${0%/*} && echo $PWD/${0##*/}) )"
source "$SCRIPT_DIR/rmuxid"
TMUXCONF="$RMUXDIR/tmux.conf"

if [ "$1" == "attach" ]; then
	if [ -e "$RMUXDIR/tmux-attach-hook"  ]; then
		"$RMUXDIR/tmux-attach-hook"
	fi
fi

if [ -e "$RMUXDIR/tmux-bin" ]; then
	"$RMUXDIR/tmux-bin" -f "$TMUXCONF" "$@"
else
	if [ -e /opt/csw/bin/tmux ]; then
		/opt/csw/bin/tmux -f "$TMUXCONF" "$@"
	else
		tmux -f "$TMUXCONF" "$@"
	fi
fi

if [ "$1" == "attach" ]; then
	if [ -e "$RMUXDIR/tmux-detach-hook"  ]; then
		"$RMUXDIR/tmux-detach-hook"
	fi
fi



