" Basic initialization for RMUX change if need, add your settings
set nocp
let &rtp .= expand(",$RMUXDIR/vim,$RMUXDIR/vim/after")
let $PYTHONPATH .= expand(":$RMUXDIR/jedi")

call pathogen#infect()
call pathogen#helptags()

syntax on
filetype plugin on

#  Add your settings here
